FROM mysql:latest

COPY script.sh /docker-entrypoint-initdb.d/

# Defina as variáveis de ambiente necessárias
ENV DB_HOST=localhost
ENV DB_ROOT_USER=root
ENV DB_ROOT_PASSWORD=root_password
ENV DB_NAME=mydatabase
ENV DB_USER=myuser
ENV DB_PASSWORD=mypassword

# Expõe a porta padrão do MySQL
EXPOSE 3306
